version: '3'
services:
    babyproxy:
        hostname: babyproxy
        read_only: true
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: babyproxy
        ports:
            - "3817:3817"